apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: testkube
  namespace: cluster-config
spec:
  interval: 5m0s
  releaseName: testkube
  targetNamespace: testkube
  chart:
    spec:
      chart: testkube
      sourceRef:
        kind: HelmRepository
        name: testkube
        namespace: cluster-config
      version: "1.15.25"
  values:
    testkube-dashboard:
      enabled: "true"
      ingress:
        className: "nginx"
        enabled: "true" 
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          cert-manager.io/cluster-issuer: letsencrypt-dev
          acme.cert-manager.io/http01-edit-in-place: "true"
        path: /
        hosts:
          - podinfo.local
        tlsenabled: "false"
        tls:
          - hosts:
              - podinfo.local
            secretName: testkube-cert-secret
      apiServerEndpoint: "podinfo.local/results"
    testkube-api:
      uiIngress:
        enabled: true
        className: "nginx"
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          nginx.ingress.kubernetes.io/rewrite-target: /$1
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
        path: /results/(v\d/.*)
        hosts:
          - podinfo.local
        tlsenabled: "false"
        tls:
          - hosts:
              - podinfo.local
            secretName: testkube-cert-secret

