apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: testkube
  namespace: cluster-config
spec:
  interval: 5m0s
  releaseName: testkube
  targetNamespace: testkube
  chart:
    spec:
      chart: testkube
      sourceRef:
        kind: HelmRepository
        name: testkube
        nnamespace: cluster-config
      version: "1.15.25"
  values:
   testkube-dashboard:
     enabled: "true"
     ingress:
       enabled: "true" 
   testkube-api:
     ingress:
       enabled: "true"

