apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ../base/podinfo
  - ../base/ffc-demo-web 
  - ingress.yaml
  - priority-class.yaml

patches:
  # - path: podinfo-values.yaml
  - path: ffc-demo-web-values.yaml  
